### ISSUE TITLE
Determine input and output of running API

### ISSUE THREAD

**Issue by ckammerl** [ClairvoyantChameleon/Run-Planner#16]

**Comment by chrisgrovers** [comment]
API: We will use google geocoding api on the backend, and google maps/directions api on the frontend

backend: We will need a start and end point [until we determine our routing algorithm]. Start and end point will then be used to get coordinates with the google geocoding api.
server will return coordinates to server

frontend: Will need a start and end point to send to server
Server will return GPS coordinates to be mapped with google maps api, and will have a route displayed with google directions api
